### ISSUE TITLE
AttributeError: /usr/local/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music#344]
In GitLab by @J4gQBqqR on Sep 11, 2022, 08:29

```
Traceback (most recent call last):
  File "/usr/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/usr/lib/python3/dist-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 48, in <module>
    from .dbus import dbus_propagate, DBusManager
  File "/usr/lib/python3/dist-packages/sublime_music/dbus/__init__.py", line 1, in <module>
    from .manager import dbus_propagate, DBusManager
  File "/usr/lib/python3/dist-packages/sublime_music/dbus/manager.py", line 13, in <module>
    from ..players import PlayerManager
  File "/usr/lib/python3/dist-packages/sublime_music/players/__init__.py", line 1, in <module>
    from .manager import PlayerDeviceEvent, PlayerEvent, PlayerManager
  File "/usr/lib/python3/dist-packages/sublime_music/players/manager.py", line 7, in <module>
    from .mpv import MPVPlayer  # noqa: F401
  File "/usr/lib/python3/dist-packages/sublime_music/players/mpv.py", line 5, in <module>
    import mpv
  File "/usr/lib/python3/dist-packages/mpv.py", line 531, in <module>
    _handle_func('mpv_detach_destroy',          [],                                         None, errcheck=None)
  File "/usr/lib/python3/dist-packages/mpv.py", line 478, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libmpv.so.2: undefined symbol: mpv_detach_destroy
```

See:[here](https://github.com/jellyfin/jellyfin-mpv-shim/issues/246) and [here](
https://github.com/jaseg/python-mpv/issues/192).

When using compiled MPV from latest git master branch, the above error will show up.

It seems that by updating to latest dependencies, this issue will be gone. Could you check and update the dependencies?

**Comment by sumnerevans** [comment]
In GitLab by @J4gQBqqR on Sep 20, 2022, 13:14

Hi, I saw that the dependency of python-mpv is updated. Will there be a release recently to take advangtage of this fix?

Thank you.
