### ISSUE TITLE
Won't initialize on Python 3.11

### ISSUE THREAD

**Issue by rockerbacon** [sublime-music/sublime-music#386]
Installed using pip on Fedora 37. sublime-music-0.11.16, according to the pip logs.

Here are the error logs:
```
Traceback (most recent call last):
  File "/usr/local/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/usr/local/lib/python3.11/site-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/usr/local/lib/python3.11/site-packages/sublime_music/app.py", line 38, in <module>
    from .adapters import (
  File "/usr/local/lib/python3.11/site-packages/sublime_music/adapters/__init__.py", line 11, in <module>
    from .manager import AdapterManager, DownloadProgress, Result, SearchResult
  File "/usr/local/lib/python3.11/site-packages/sublime_music/adapters/manager.py", line 33, in <module>
    from sublime_music.config import ProviderConfiguration
  File "/usr/local/lib/python3.11/site-packages/sublime_music/config.py", line 12, in <module>
    from .ui.state import UIState
  File "/usr/local/lib/python3.11/site-packages/sublime_music/ui/state.py", line 41, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'sublime_music.adapters.adapter_base.AlbumSearchQuery'> for field current_album_search_query is not allowed: use default_factory
```

This was supposed to have already been fixed, according to #346, but the issue is still present.

**Comment by sumnerevans** [comment]
Fixed already in fd40be6809e781d90e64e479a9260efbcbf67f60
