### ISSUE TITLE
Playback with mpv 0.38 is broken

### ISSUE THREAD

**Issue by baldurmen** [sublime-music/sublime-music#462]
Using libmpv 0.38, I get the following trace when trying to play an album:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime_music/dbus/manager.py", line 24, in wrapper
    function(*args)
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 629, in on_play_pause
    self.play_song(self.app_config.state.current_song_index)
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 1415, in play_song
    song_details_future.add_done_callback(
  File "/usr/lib/python3/dist-packages/sublime_music/adapters/manager.py", line 140, in add_done_callback
    fn(self, *args)
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 1416, in <lambda>
    lambda f: do_play_song(self.song_playing_order_token, f.result())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sublime_music/dbus/manager.py", line 24, in wrapper
    function(*args)
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 1166, in do_play_song
    self.player_manager.play_media(
  File "/usr/lib/python3/dist-packages/sublime_music/players/manager.py", line 188, in play_media
    current_player.play_media(uri, progress, song)
  File "/usr/lib/python3/dist-packages/sublime_music/players/mpv.py", line 137, in play_media
    self.mpv.command(
  File "/usr/lib/python3/dist-packages/mpv.py", line 1233, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "/usr/lib/python3/dist-packages/mpv.py", line 148, in raise_for_ec
    raise ex
ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7f1bc19d8cb0>, <mpv.LP_MpvNode object at 0x7f1c377c4950>, <mpv.LP_MpvNode object at 0x7f1c377c48c0>))

````

This can also be replicated in the testsuite:

```
=================================== FAILURES ===================================
__________________________________ test_play ___________________________________

    def test_play():
        empty_fn = lambda *_, **__: None
        mpv_player = MPVPlayer(empty_fn, empty_fn, empty_fn, empty_fn, {"Replay Gain": "Disabled"})
    
        song_path = Path(__file__).parent.joinpath("mock_data/test-song.mp3")
>       mpv_player.play_media(str(song_path), timedelta(seconds=10), Song())

tests/player_tests/mpv_tests.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sublime_music/players/mpv.py:137: in play_media
    self.mpv.command(
/usr/lib/python3/dist-packages/mpv.py:1233: in command
    _mpv_command_node(self.handle, ppointer, out)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

kls = <class 'mpv.ErrorCode'>, ec = -4
func = <_FuncPtr object at 0x7fb707ba3110>
args = ((<MpvHandle object at 0x7fb6f7d44680>, <mpv.LP_MpvNode object at 0x7fb6f7d46600>, <mpv.LP_MpvNode object at 0x7fb6f7d46570>),)
ex = ValueError('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7fb6f7d44680>, <mpv.LP_MpvNode object at 0x7fb6f7d46600>, <mpv.LP_MpvNode object at 0x7fb6f7d46570>))

    @classmethod
    def raise_for_ec(kls, ec, func, *args):
        ex = kls.exception_for_ec(ec, *args)
        if ex:
>           raise ex
E           ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7fb6f7d44680>, <mpv.LP_MpvNode object at 0x7fb6f7d46600>, <mpv.LP_MpvNode object at 0x7fb6f7d46570>))

/usr/lib/python3/dist-packages/mpv.py:148: ValueError
```

**Comment by baldurmen** [comment]
It seems this spawns from the version of python-mpv we use in Debian. This issue has been fixed in the newest release:

https://github.com/jaseg/python-mpv/commit/d96eaf7e64f1063ae16f88abfaa14c2997b3291d

**Comment by baldurmen** [comment]
Ah yes, and for posterity, this also needs this PR to be fixed: https://github.com/sublime-music/sublime-music/pull/461
