### ISSUE TITLE
[BUG] Unable to play any music due to `Invalid value for mpv parameter`

### ISSUE THREAD

**Issue by adam900710** [sublime-music/sublime-music#463]
The calltrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/sublime_music/dbus/manager.py", line 24, in wrapper
    function(*args)
  File "/usr/lib/python3.12/site-packages/sublime_music/app.py", line 629, in on_play_pause
    self.play_song(self.app_config.state.current_song_index)
  File "/usr/lib/python3.12/site-packages/sublime_music/app.py", line 1415, in play_song
    song_details_future.add_done_callback(
  File "/usr/lib/python3.12/site-packages/sublime_music/adapters/manager.py", line 140, in add_done_callback
    fn(self, *args)
  File "/usr/lib/python3.12/site-packages/sublime_music/app.py", line 1416, in <lambda>
    lambda f: do_play_song(self.song_playing_order_token, f.result())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/sublime_music/dbus/manager.py", line 24, in wrapper
    function(*args)
  File "/usr/lib/python3.12/site-packages/sublime_music/app.py", line 1166, in do_play_song
    self.player_manager.play_media(
  File "/usr/lib/python3.12/site-packages/sublime_music/players/manager.py", line 188, in play_media
    current_player.play_media(uri, progress, song)
  File "/usr/lib/python3.12/site-packages/sublime_music/players/mpv.py", line 137, in play_media
    self.mpv.command(
  File "/usr/lib/python3.12/site-packages/mpv.py", line 1227, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "/usr/lib/python3.12/site-packages/mpv.py", line 142, in raise_for_ec
    raise ex
ValueError: ('Invalid value for mpv parameter', -4, (<MpvHandle object at 0x7d117b0733d0>, <mpv.LP_MpvNode object at 0x7d11604b28d0>, <mpv.LP_MpvNode object at 0x7d11604b2250>))
```

Version: v0.12.0.r17.g0b4ba69a7ff7
Distro: Archlinux (sublime-music-git AUR package)
python-mpv 1.0.5-2

**Comment by alscaldas** [comment]
Any news on this?

sublime-music:  v0.12.0 installed from AUR (I've also tried sublime-music-git and via pip. same result).
python-mpv: 1.0.7-1

**Comment by Estebiu** [comment]
Can confirm this is happening on my end too.

**Comment by sumnerevans** [comment]
If someone wants to fix the test on https://github.com/sublime-music/sublime-music/pull/461, I'll merge it.

**Comment by Jucgshu** [comment]
Works :+1:

**Comment by alscaldas** [comment]
@Jucgshu what exactly works? How have you did it work?

**Comment by Jucgshu** [comment]
Playing now works by applying patch #461.
